version: '3.9'

services:
  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    command: ["sh", "-c", "npm install && npm run dev --host=0.0.0.0"]
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    networks:
      - app-network

  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
